### ISSUE TITLE
Courser position

### ISSUE THREAD

**Issue by Mahemudhasan01** [bdecentgmbh/moodle-local_learningtools#14] opened 2022-03-27 18:08 UTC
When a user clicks on the pensile button for notes popup box opens up for notes at that time courser position start from mid of the box instead of the top.

**Comment by stefanscholz** [comment] 2022-03-27 18:11
Hi!

Thanks for contacting us!

I don't understand exactly what you mean unfortunately - can you provide more details on the issue, maybe with a screen shot or capture to demonstrate?

Thanks 
Stefan

**Comment by stefanscholz** [comment] 2022-03-30 14:52
Closing this issue until feedback from reporter. (Was not able to reproduce issue)

**Closed by stefanscholz** 2022-03-30 14:52 UTC
